<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/security_bootstrap.php';
sentryiq_security_bootstrap();
sentryiq_require_auth();

$configFile=dirname(__DIR__, 2).'/sentryiq_config.php';$config=is_file($configFile)?require $configFile:[];$dataDir=is_array($config)?rtrim((string)($config['data_dir']??''),'/'):'';
if($dataDir===''||!str_starts_with($dataDir,'/')||!is_dir($dataDir)||is_link($dataDir)){http_response_code(503);exit('SentryIQ secure runtime is unavailable.');}
if(is_file($dataDir.'/vault_engine.php')&&!is_link($dataDir.'/vault_engine.php'))require_once $dataDir.'/vault_engine.php';
require_once dirname(__DIR__, 2).'/cloud/Gallery/Image/GallerySettings.php';
use SentryIQCloud\Gallery\Image\GallerySettings;
$csrf=sentryiq_csrf_token();$message='';$messageClass='success';
if($_SERVER['REQUEST_METHOD']==='POST'){sentryiq_require_csrf();try{$savedQuality=filter_input(INPUT_POST,'saved_quality',FILTER_VALIDATE_INT);$savedMaxDimension=filter_input(INPUT_POST,'saved_max_dimension',FILTER_VALIDATE_INT);$thumbnailQuality=filter_input(INPUT_POST,'thumbnail_quality',FILTER_VALIDATE_INT);$thumbnailMaxDimension=filter_input(INPUT_POST,'thumbnail_max_dimension',FILTER_VALIDATE_INT);$previewQuality=filter_input(INPUT_POST,'preview_quality',FILTER_VALIDATE_INT);$previewMaxDimension=filter_input(INPUT_POST,'preview_max_dimension',FILTER_VALIDATE_INT);if($savedQuality===false||$savedQuality===null||$savedQuality<1||$savedQuality>100)throw new RuntimeException('Saved file quality must be between 1 and 100.');if($savedMaxDimension===false||$savedMaxDimension===null||$savedMaxDimension<0||$savedMaxDimension>8000)throw new RuntimeException('Saved file resolution must be between Original and 8000 pixels.');if($thumbnailQuality===false||$thumbnailQuality===null||$thumbnailQuality<1||$thumbnailQuality>100)throw new RuntimeException('Thumbnail quality must be between 1 and 100.');if($thumbnailMaxDimension===false||$thumbnailMaxDimension===null||$thumbnailMaxDimension<100||$thumbnailMaxDimension>2000)throw new RuntimeException('Thumbnail resolution must be between 100 and 2000 pixels.');if($previewQuality===false||$previewQuality===null||$previewQuality<1||$previewQuality>100)throw new RuntimeException('Preview quality must be between 1 and 100.');if($previewMaxDimension===false||$previewMaxDimension===null||$previewMaxDimension<200||$previewMaxDimension>4000)throw new RuntimeException('Preview resolution must be between 200 and 4000 pixels.');GallerySettings::save($dataDir,['saved_quality'=>$savedQuality,'saved_max_dimension'=>$savedMaxDimension,'thumbnail_quality'=>$thumbnailQuality,'thumbnail_max_dimension'=>$thumbnailMaxDimension,'preview_quality'=>$previewQuality,'preview_max_dimension'=>$previewMaxDimension,'preserve_transparency'=>isset($_POST['preserve_transparency'])]);$message='Gallery settings saved successfully.';if(function_exists('log_security_event')){log_security_event('GALLERY_SETTINGS_UPDATED',get_visitor_ip(),$_SESSION['app_username']??'unknown');}}catch(Throwable $exception){$message=$exception->getMessage()!==''?$exception->getMessage():'Gallery settings could not be saved.';$messageClass='error';}}
$settings=GallerySettings::load($dataDir);
function gallerySettingValue(int $value,int $originalLabel=0):string{return $value===$originalLabel?'Original':(string)$value.' px';}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="<?php echo htmlspecialchars($csrf,ENT_QUOTES,'UTF-8'); ?>"><title>SentryIQ — Gallery Settings</title><link rel="stylesheet" href="pm_style.css"></head><body><div class="box">
<div class="sentryiq-page-header"><div class="sentryiq-vault-brand-wrap"><img class="sentryiq-vault-banner" src="sentryiq-logo-wide.webp" width="1952" height="588" alt="SentryIQ"><span class="sentryiq-vault-status">Gallery Settings</span></div><div class="sentryiq-mobile-header-actions"><form method="POST" class="sentryiq-lock-form"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf,ENT_QUOTES,'UTF-8'); ?>"><input type="hidden" name="lock_vault" value="1"><button type="submit" class="btn btn-primary sentryiq-lock-button">Lock Vault</button></form><div class="vault-mobile-menu-bar"><button type="button" class="vault-mobile-menu-toggle" aria-expanded="false" aria-controls="vault-mobile-menu"><span class="vault-mobile-menu-icon" aria-hidden="true">☰</span><span id="vault-mobile-menu-label">Menu</span></button></div></div></div>
<div id="vault-mobile-menu" class="vault-tabs"><button class="tab-btn" type="button" onclick="window.location.href='index.php?pane=view'">📋 Vault</button><button class="tab-btn" type="button" onclick="window.location.href='documents.php'">📄 Docs</button><button class="tab-btn" type="button" onclick="window.location.href='gallery.php'">🖼️ Gallery</button><button class="tab-btn active" type="button" onclick="window.location.href='index.php?pane=settings'">⚙️ System</button><form method="POST" class="vault-menu-lock-form"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf,ENT_QUOTES,'UTF-8'); ?>"><input type="hidden" name="lock_vault" value="1"><button type="submit" class="tab-btn vault-menu-lock-button">🔒 Lock Vault</button></form></div>
<div class="form-box"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;"><div><h2 style="margin-bottom:6px;">🖼️ Gallery Settings</h2><p style="margin-top:0;color:#666;">Control the fixed resolution and encoding quality of saved images, thumbnails and previews.</p></div><a href="index.php?pane=settings" class="btn" style="text-decoration:none;background:#6c757d;color:#fff;">← Back to System</a></div><?php if($message!==''): ?><p class="<?php echo htmlspecialchars($messageClass,ENT_QUOTES,'UTF-8'); ?>"><?php echo htmlspecialchars($message,ENT_QUOTES,'UTF-8'); ?></p><?php endif; ?><form method="POST" style="margin-top:20px;"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf,ENT_QUOTES,'UTF-8'); ?>">
<div style="padding:16px;border:1px solid #e9ecef;border-radius:10px;background:#f8f9fa;margin-bottom:20px;"><h3 style="margin-top:0;">Saved File</h3><div class="form-group"><label for="saved_max_dimension">Resolution: <strong id="saved-resolution-value"><?php echo htmlspecialchars(gallerySettingValue((int)$settings['saved_max_dimension'])); ?></strong></label><input id="saved_max_dimension" type="range" name="saved_max_dimension" min="0" max="8000" step="100" value="<?php echo (int)$settings['saved_max_dimension']; ?>" style="width:100%;" oninput="document.getElementById('saved-resolution-value').textContent=this.value==='0'?'Original':this.value+' px'"><small style="display:block;margin-top:5px;color:#777;">Maximum longest side. 0 means Original and preserves the uploaded dimensions.</small></div><div class="form-group"><label for="saved_quality">Quality: <strong id="saved-quality-value"><?php echo (int)$settings['saved_quality']; ?></strong></label><input id="saved_quality" type="range" name="saved_quality" min="1" max="100" value="<?php echo (int)$settings['saved_quality']; ?>" style="width:100%;" oninput="document.getElementById('saved-quality-value').textContent=this.value"><small style="display:block;margin-top:5px;color:#777;">Fixed WebP encoding quality for the stored image.</small></div></div>
<div style="padding:16px;border:1px solid #e9ecef;border-radius:10px;background:#f8f9fa;margin-bottom:20px;"><h3 style="margin-top:0;">Thumbnail</h3><div class="form-group"><label for="thumbnail_max_dimension">Resolution: <strong id="thumbnail-resolution-value"><?php echo (int)$settings['thumbnail_max_dimension']; ?> px</strong></label><input id="thumbnail_max_dimension" type="range" name="thumbnail_max_dimension" min="100" max="2000" step="50" value="<?php echo (int)$settings['thumbnail_max_dimension']; ?>" style="width:100%;" oninput="document.getElementById('thumbnail-resolution-value').textContent=this.value+' px'"><small style="display:block;margin-top:5px;color:#777;">Maximum longest side of generated Gallery thumbnails.</small></div><div class="form-group"><label for="thumbnail_quality">Quality: <strong id="thumbnail-quality-value"><?php echo (int)$settings['thumbnail_quality']; ?></strong></label><input id="thumbnail_quality" type="range" name="thumbnail_quality" min="1" max="100" value="<?php echo (int)$settings['thumbnail_quality']; ?>" style="width:100%;" oninput="document.getElementById('thumbnail-quality-value').textContent=this.value"><small style="display:block;margin-top:5px;color:#777;">Fixed WebP encoding quality for thumbnails.</small></div></div>
<div style="padding:16px;border:1px solid #e9ecef;border-radius:10px;background:#f8f9fa;margin-bottom:20px;"><h3 style="margin-top:0;">Preview</h3><div class="form-group"><label for="preview_max_dimension">Resolution: <strong id="preview-resolution-value"><?php echo (int)$settings['preview_max_dimension']; ?> px</strong></label><input id="preview_max_dimension" type="range" name="preview_max_dimension" min="200" max="4000" step="100" value="<?php echo (int)$settings['preview_max_dimension']; ?>" style="width:100%;" oninput="document.getElementById('preview-resolution-value').textContent=this.value+' px'"><small style="display:block;margin-top:5px;color:#777;">Maximum longest side used for the image shown in the Gallery viewer.</small></div><div class="form-group"><label for="preview_quality">Quality: <strong id="preview-quality-value"><?php echo (int)$settings['preview_quality']; ?></strong></label><input id="preview_quality" type="range" name="preview_quality" min="1" max="100" value="<?php echo (int)$settings['preview_quality']; ?>" style="width:100%;" oninput="document.getElementById('preview-quality-value').textContent=this.value"><small style="display:block;margin-top:5px;color:#777;">Fixed WebP encoding quality for Gallery previews.</small></div></div>
<div class="form-group"><label style="display:flex;align-items:center;gap:10px;cursor:pointer;"><input type="checkbox" name="preserve_transparency" value="1" <?php echo $settings['preserve_transparency']?'checked':''; ?> style="width:18px;height:18px;"><span>Preserve image transparency</span></label><small style="display:block;margin-top:5px;color:#777;">Keeps transparent backgrounds when the source image supports transparency.</small></div>
<button type="submit" class="btn btn-primary" style="margin-top:20px;">💾 Save Gallery Settings</button></form></div></div><script>document.addEventListener('DOMContentLoaded',function(){var toggle=document.querySelector('.vault-mobile-menu-toggle'),menu=document.getElementById('vault-mobile-menu');if(toggle&&menu)toggle.addEventListener('click',function(){var open=menu.classList.toggle('mobile-open');toggle.setAttribute('aria-expanded',open?'true':'false');});});</script></body></html>
